# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Run NPM scripts

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  install:
    name: Install
    runs-on: buildjet-2vcpu-ubuntu-2204-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Node.js modules
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Setup Node.js
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Yarn install
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile

  lint:
    name: Lint
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    needs: install

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Restore Node.js modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          fail-on-cache-miss: true

      - name: Yarn lint:strict
        run: yarn lint:strict

  build:
    name: Build
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    needs: install

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Restore Node.js modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          fail-on-cache-miss: true

      - name: Yarn build
        run: yarn build
